### ISSUE TITLE
#676 still not fixed. at GL3.0, have to continue moving to show.

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#677] opened 2021-07-24 01:56 UTC
### Description

https://github.com/leezer3/OpenBVE/issues/676 is still happen.
And we have to continueing moving for all parts showing.
Left mouse drag is not show all.
Right mouse drag can show when we are dragging.
ten key and direction keys moving is show when we are any key only presssing.
When we are nothing to do,  some parts is not display.
Please look this movie.
I don't know why, but this not displaying happens at only the first time run.
Second time or after, this is not happen.

https://user-images.githubusercontent.com/22734699/126854286-f7cc0135-a881-4a16-9cb1-3b9865503a4d.mp4

Delay https://github.com/leezer3/OpenBVE/issues/676 is direction key or left button drag only.
Ritht drag and ten key moving is not happen.
Both is not happen at extensions.cfg.

### Reproduction

Any an .animated object.
Please use my Series-E5.
https://drive.google.com/uc?export=download&id=15B98GOoz19jV4eWGiaiwRi6ReHkSBAjS

## Route

This issue happens at ObjectViewer.
So it is not use any route data.

## Train

This issue happens at ObjectViewer.
But, to load Extensisons.cfg, need Train.

## Logs
This issue is not output any logs.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by leezer3** [comment] 2021-07-26 09:12
I can't reproduce that- Everything appears to work here :(

Does this version work any better for you?
[AlternateTest.zip](https://github.com/leezer3/OpenBVE/files/6876987/AlternateTest.zip)

I've changed the way the reset is made (by triggering on every frame in Object Viewer, as opposed to camera movement)

**Comment by ginga81** [comment] 2021-07-26 10:46
AlternateTest.zip is seems work correctly!
All keys and mouse moving at GL3.0 are not delay.

**Comment by leezer3** [comment] 2021-07-26 11:27
Good, merged that to master, so the latest (as of about 10 mins or so ago) should now be good.

**Closed by leezer3** 2021-07-26 11:27 UTC
