### ISSUE TITLE
Transparency trouble with new renderer on 1.7.1.4, loading screen and proccessing bar both not shown only linux

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#466] opened 2020-04-26 00:56 UTC
Old renderer is not happen transparency issue.
Loading screen trouble is only on Linux, not happen on Windows.

This trouble happens at my tohoku-shinkansen route.
http://midnightexpginga81.web.fc2.com/touhoku_shinkansen/route_data/Touhogu-Shinkansen-Routedata-fromSendai_v0.06.zip
This screenshots are now creating new version, so difference. but most objects are the same, and also happens.
The cars are all of my released outer-view object, Series-200, 925, E5  and E6.

I tested the daily-builds.
OpenBVE-2020-04-20.zip:OK
OpenBVE-2020-04-21.zip:NG

![new-render](https://user-images.githubusercontent.com/22734699/80294466-12eb0580-87a4-11ea-843b-037ab03f78fd.jpg)
![old-render](https://user-images.githubusercontent.com/22734699/80294468-141c3280-87a4-11ea-860d-4f4e15ed3d94.jpg)

At objectViewer's options_ov.cfg, isUseNewRenderer key change also I tested at 1.7.1.4's.
There are not differense about transparency.
This object that I tested.
Touhogu-Shinkansen-Objectdata-v0.15.zip
https://onedrive.live.com/redir?resid=2E630AFCBBE39699%21159
Object/OpenOBJs/Dike&Wall&Roads/Shinkansen/Pole/PoleR.csv
![new-render-ov](https://user-images.githubusercontent.com/22734699/80298212-e693b100-87c4-11ea-9742-e78ef8d4b2e1.jpg)
![old-render-ov](https://user-images.githubusercontent.com/22734699/80298215-ea273800-87c4-11ea-8cc4-21d2afb9d360.jpg)

Please check these troubles.

**Comment by leezer3** [comment] 2020-04-26 06:20
Will do.

I suspect something funny in the drivers (default state maybe?) as I did quite a bit of testing on Mac with this and definitely didn't see any glitches :(

**Comment by s520** [comment] 2020-04-26 06:35
When NewRenderer is enabled, ObjectViewer's key display is not correct to begin with.
After April 21:
![キャプチャ](https://user-images.githubusercontent.com/29241703/80299892-0205b880-87d3-11ea-91b9-aa0b61578e67.PNG)

Probably the cause is https://github.com/leezer3/OpenBVE/commit/4ab05b45fde9df1663049bb94159956948268293.

The confirmed environment is as follows:
- Windows 10 x64
- Intel Core i5-10210U
- Intel UHD Graphics

**Comment by leezer3** [comment] 2020-04-26 17:57
It's typical, nobody notices anything broken until you push a release :)

I've fixed the key display for both viewers- Forgot to reset the blending type; The overlays are drawn with the old renderer. Need to sort out text drawing with the new renderer ( @LabRatAndy has done some on this in his branch)

The brightness issue turned out to be a rather more major oversight- We forgot to reverse the Z of the normal when adding it to the VAO.

**Comment by ginga81** [comment] 2020-04-26 18:20
My PC's spec:
OS:Ubuntu 18.04.4 LTS 64bit
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16 
Graphics board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-46-generic, LLVM 9.0.0)
propraietary AMD Graphics driver

**Comment by leezer3** [comment] 2020-04-26 18:45
OK, might have it nailed now- Give the latest a try when it builds in a few minutes.....

Partially reverted https://github.com/leezer3/OpenBVE/commit/4ab05b45fde9df1663049bb94159956948268293 after fixing the Z-normal issue, as now all of a sudden some things work somewhat better.

**Comment by ginga81** [comment] 2020-04-26 20:21
I tested OpenBVE-2020-04-26.zip rapidly.
the result is as shown by below.
![new-render2](https://user-images.githubusercontent.com/22734699/80318642-847b9000-8846-11ea-90d2-1f0dfc79f07a.jpg)
![old-render2](https://user-images.githubusercontent.com/22734699/80318548-dec82100-8845-11ea-84e3-5e32ad03f3f2.jpg)
around UV's area transparency is fine.
the another UV such as this tree, overlaps the another texture is not shown.
And transparent light color is not paint.
But, these issue is already happen at 1.7.1.3.
So, I think that this is the another issue.

**Comment by leezer3** [comment] 2020-04-26 21:28
Which exact object file is that powerline please?

I can't immediately find it, and it'll be a lot easier to test if I can isolate it.

The tree looks like a Z-sort issue.
 I'm guessing the powerline is part of a somewhat larger object and overlaps it?
These have always been problematic.

**Comment by ginga81** [comment] 2020-04-27 01:30
Oh... I am sorry.
This object is a new version for my route.
So, current version is not bundle.
Please test this sample route.
This route is using two objects that is the same screenshot above.
So, OpenBVE-2020-04-26.zip and 1.7.1.4 happens also.
[transparent-trouble-sampleroute.zip](https://github.com/leezer3/OpenBVE/files/4536911/transparent-trouble-sampleroute.zip)

**Comment by ginga81** [comment] 2020-04-27 04:06
I and S520 both tested below.
This test is using by transparent-trouble-sampleroute.zip.
The result is shown below.
One of problem, light's exposure UV texture affects transmission through. (Is this may be Z-order?)
The another problem is Ground color is very brightness.
These probrems, we doubt that the result by as below, causes by Route.AmbientLight and Track.fog.

These problems are by route's comand affects.
So, these problems are cannot be reproduced at ObjectViewer.

Light's exposure UV texture affects transmission through
OpenBVE-2020-04-26.zip
Route.AmbientLight enable
NewRenderer			NG
OldRenderer			NG		

Route.AmbientLight disable
NewRenderer			OK
OldRenderer			OK

1.7.1.4
Route.AmbientLight enable
NewRenderer			NG
OldRenderer			NG

Route.AmbientLight disable
NewRenderer			OK
OldRenderer			OK

Ground color is very brightness
OpenBVE-2020-04-26.zip
Track.Fog enable
NewRenderer			white
OldRenderer			green(normal)
Track.Fog disable
NewRenderer			green(normal)
OldRenderer			green(normal)

1.7.1.4
Track.Fog enable
NewRenderer			white
OldRenderer			green(normal)
Track.Fog disable
NewRenderer			green(normal)
OldRenderer			green(normal)

**Comment by leezer3** [comment] 2020-04-27 12:30
Try the latest-
This should be somewhat better. (We were incorrectly transforming the normals in the shader; Should have been untransformed)

There's still something funny going on with the normals on your lights (Will investigate later- going to work), which means the color is still missing, but both renderers are now I believe identical.

**Comment by ginga81** [comment] 2020-04-27 13:42
I tested at OpenBVE-2020-04-27.zip.
NewRenderer option is on or off, both option is crashed.
The train is 
https://github.com/leezer3/OpenBVE/issues/435
And the route is 
transparent-trouble-sampleroute.zip

[OpenBVE Crash- 2020.4.27[22.36].log](https://github.com/leezer3/OpenBVE/files/4539977/OpenBVE.Crash-.2020.4.27.22.36.log)

**Comment by s520** [comment] 2020-04-27 13:45
Variable type is not defined.
https://github.com/leezer3/OpenBVE/blob/32376c5a5a1a05fad4c330db99665e68c3221edd/assets/Shaders/default.vert#L52

I think the problem with Fog is that the Fog expression in the shader is wrong.
I am investigating it.

**Comment by leezer3** [comment] 2020-04-27 13:49
That's odd, it works on Windows.

I think the fog issue is likely normal related though- Turn on the normal display and toggle between renderer types in route viewer.

**Comment by s520** [comment] 2020-04-27 13:53
Error log is output on my Windows. (F9)
The screen says "New (GL 3.0)", but this only reflects the option settings, not the fallback to legacy.

**Comment by leezer3** [comment] 2020-04-27 13:59
Dunno.

Maybe I had an uncommitted change?
Either way, needs sorting.

**Comment by s520** [comment] 2020-04-27 14:15
Perhaps I was able to fix Fog.
I will open PR...

**Comment by leezer3** [comment] 2020-04-27 19:45
Try this vertex shader:
```
#version 150

struct Light
{
    vec3 position;
    vec3 ambient;
    vec3 diffuse;
    vec3 specular;
};

struct MaterialColor
{
    vec4 ambient;
    vec4 diffuse;
    vec4 specular;
	vec3 emission;
    float shininess;
	bool isEmissive;
}; 

in vec3 iPosition;
in vec3 iNormal;
in vec2 iUv;
in vec4 iColor;

uniform mat4 uCurrentProjectionMatrix;
uniform mat4 uCurrentModelViewMatrix;
uniform mat4 uCurrentTextureMatrix;

uniform bool uIsLight;
uniform bool uIsEmissive;
uniform Light uLight;
uniform MaterialColor uMaterial;
uniform bool uIsFog;
uniform float uFogStart;
uniform float uFogEnd;

out vec2 oUv;
out vec4 oColor;
out float oFogFactor;

void main()
{
	vec4 viewPos = uCurrentModelViewMatrix * vec4(vec3(iPosition.x, iPosition.y, -iPosition.z), 1.0);
	gl_Position = uCurrentProjectionMatrix * viewPos;

	// Lighting
	// Ambient
	vec4 ambient  = vec4(uLight.ambient.x, uLight.ambient.y, uLight.ambient.z, 1.0) * uMaterial.ambient;

	// Diffuse
	vec3 viewNormal = normalize(vec3(iNormal.x, iNormal.y, -iNormal.z);
	vec3 eye = normalize(-viewPos.xyz);
	float diff = max(dot(viewNormal, uLight.position), 0.0);
	vec4 diffuse = vec4(uLight.diffuse.x, uLight.diffuse.y, uLight.diffuse.z, 1.0) * (diff * uMaterial.diffuse);

	// Specular
	vec4 specular = vec4(0.0);

	if(diff > 0.0)
	{
		vec3 halfVector = normalize(uLight.position + eye);
		float spec = pow(max(dot(halfVector, viewNormal), 0.0), uMaterial.shininess);
		specular = vec4(uLight.specular.x, uLight.specular.y, uLight.specular.z, 1.0) * (spec * uMaterial.specular);
	}

	// Fog
	oFogFactor = 1.0;

	if (uIsFog)
	{
		oFogFactor *= clamp((uFogEnd - length(viewPos)) / (uFogEnd - uFogStart), 0.0, 1.0);
	}

	oUv = (uCurrentTextureMatrix * vec4(iUv, 1.0, 1.0)).xy;

	oColor = iColor;

	if (uIsLight)
	{
		vec4 result;
		if(uMaterial.isEmissive)
		{
			vec4 result = clamp(ambient + diffuse + specular + vec4(uMaterial.emission.x, uMaterial.emission.y, uMaterial.emission.z, 1.0), 0.0, 1.0);
			oColor *= result;
		}
		else
		{
			vec4 result = clamp(ambient + diffuse + specular, 0.0, 1.0);
			oColor *= result;
		}
		
		
	}
	else
	{
		vec4 globalAmbient = vec4(1.0);
		oColor *= globalAmbient * uMaterial.ambient;
	}
}
```
That's what I thought I'd committed....
With this, loading the provided routefile above and toggling between the two renderers has zero discernable effect.

**Comment by leezer3** [comment] 2020-04-27 19:50
Now, this is what I see with the normal display active in Route Viewer before the new renderer was introduced:
![prev](https://user-images.githubusercontent.com/7688245/80414120-6f474580-88c8-11ea-98ec-7e49c9258f0b.png)

Using the GL1.2 render path (verified by stepping in the debugger), I now see this:
![new](https://user-images.githubusercontent.com/7688245/80414172-85550600-88c8-11ea-9630-a2509dbc9299.png)

Reading the code says that there have been no changes to the normal rendering.
Thus, I think we're either applying or missing a transform somewhere when we create the object.

**Comment by leezer3** [comment] 2020-04-27 20:09
Interesting-
With a basic test object in Object Viewer, I'm wondering if we're somehow loosing the Y co-ordinate of the normal.

**Comment by leezer3** [comment] 2020-04-27 20:41
Aha:
https://github.com/leezer3/OpenBVE/blob/master/source/LibRender2/BaseRenderer.cs#L1427
Typo in this line for the normal display in the *old* renderer.

**Comment by leezer3** [comment] 2020-04-27 22:38
I'm confusing myself again.....

I've now pushed some changes to your branch.
See what you think; I *think* the main issue is the light now?

This is an issue with our blending in the fragment shader somehow (the texture uses alpha channel transparency), which I can't get right at the minute :(

**Comment by leezer3** [comment] 2020-04-27 23:56
Done a bit more messing on your branch, see what you think now.

This has sorted the light (at least i hope so.....)
The main issue now is that there's a halo around some textures using alpha- See the insulators and stuff on the pylon.
?? http://www.realtimerendering.com/blog/gpus-prefer-premultiplication/ ??

**Comment by leezer3** [comment] 2020-04-28 22:10
@s520 
Another branch here with a bunch more fiddling around on:
https://github.com/leezer3/OpenBVE/tree/FogFix2

At the minute, I can't get the alpha to play nicely with the border of the texture, but otherwise it's decent, and the lights look relatively good.
The other issue is that the houses on the left are considerably darker. This is an issue back to 1.7.1.3 and prior.

Something is off somewhere with the lighting calcs....

**Comment by leezer3** [comment] 2020-04-29 10:57
@s520 
When you get a minute, please take a look at the new branch.
I've fixed the alpha borders on the textures by applying the lighting results *after* the texture. This leaves the issue that our houses on the left are darker.

Interestingly, reversing the X-cordinate of the normal gets us closer to correct in this regard, but makes other things off.

Can't explain it at the moment, but I'm tempted to merge this new branch into master (and push a further release), as it makes things much better with the stuff above.

**Comment by s520** [comment] 2020-04-29 18:25
I have a little time today, so I'll check tomorrow.

**Comment by leezer3** [comment] 2020-04-29 19:13
No trouble- This can wait I'm sure :)

**Comment by s520** [comment] 2020-04-30 15:10
I built and tried your branch.

I'm a little confused.
The issue with this comment looks the same in v1.7.0.3.
https://github.com/leezer3/OpenBVE/issues/466#issuecomment-619619294

I give him the built program and ask him to see it.

**Comment by leezer3** [comment] 2020-04-30 15:18
I thought the light color was now yellow / white as opposed to black :/

That was the major issue; The transparency is the same with both renderer.

I'll test once home.

**Comment by leezer3** [comment] 2020-04-30 19:21
See if these images help to explain (tested just now):
This is how the light now looks with my fix (correct):
![new](https://user-images.githubusercontent.com/7688245/80750279-b0856280-8b1f-11ea-86ae-25832dcc832d.png)

The GL3.0 renderer in all previous cases has looked like this:
(From your branch)
![yourfix](https://user-images.githubusercontent.com/7688245/80750339-cbf06d80-8b1f-11ea-9e4d-a64515babcdf.png)

However, the houses on the far left currently look like this: 
![housenew](https://user-images.githubusercontent.com/7688245/80750497-1b369e00-8b20-11ea-8a39-f9ba0ac3332e.png)

With the old renderer, they look like this:
![houseold](https://user-images.githubusercontent.com/7688245/80750532-2a1d5080-8b20-11ea-8a2b-34974eda571a.png)

**Comment by leezer3** [comment] 2020-04-30 19:25
The tree / light interaction at the minute I haven't touched, and are the same in all renderers.

This is a drawing order issue- In order for correct transparency, we need to draw from far to near; This seems to be being calculated from the enclosing object *not* the face itself. Might be able to redesign this, but probably a major job....

**Comment by s520** [comment] 2020-05-03 11:45
I asked him for confirmation.
In addition, I asked him to sort out the problem.

**Comment by leezer3** [comment] 2020-05-03 11:46
No trouble, thanks!

**Comment by leezer3** [comment] 2020-05-04 20:30
I've merged my branch into master.

Intending to put out a build on Wednesday with this, as there are several important improvements in this.

**Closed** 2021-06-27 18:56 UTC
