### ISSUE TITLE
Densha De Go Controller (SLPH-00051) Erratic Input From Brake Handle

### ISSUE THREAD

**Issue by RetentiveGOAT** [leezer3/OpenBVE#1019] opened 2024-04-15 12:32 UTC
### Description

As I'm operating the train with the brake handle in release, or any of the service brake notches, at random times, the train will go into emergency for a split second before re-registering the position of the brake handle.

### Reproduction

Operate any train using the DenGo SLPH-00051 controller.

### Logs

[##]([openBVE Bug Report15_04_2024.zip](https://github.com/leezer3/OpenBVE/files/14978949/openBVE.Bug.Report15_04_2024.zip)) Logs

### Related information 

* OS: Windows 11 (64-bit)
* Method of control: Densha De Go! SLPH-00051 controller with ELECOM PS1 to PC adapter

**Comment by leezer3** [comment] 2024-04-15 12:59
@MarcRiera will really have to look at this one.

**Comment by MarcRiera** [comment] 2024-04-15 21:44
@RetentiveGOAT Does it happen when moving the brake handle, or even with the controller at rest? Do you have a PlayStation to check that the controller works correctly? Could you please try cleaning the connector contacts for both the controller and the adapter?

Internally, for this controller model, brake notches are a combination of four buttons. The emergency brake notch is represented internally as all four buttons released, so OpenBVE is detecting that momentarily (for some reason) these buttons are released. I can't see where this could be failing in software, so maybe it's just dirt.

**Comment by RetentiveGOAT** [comment] 2024-04-16 00:07
It happens when the handle is at rest, and the controller is 100% functional, I've personally tested it on 3 different PlayStation 2s and an original PlayStation when I first got the controller. I also made sure to clean the contacts as well.

**Comment by MarcRiera** [comment] 2024-04-16 10:09
Thanks. I haven't recreated the issue 1:1, but I ran a couple of tests with a USB controller remapper I have that gave me problems in the past and I have an idea of what could be happening.

In my case, the adapter seems to spam the PC every few milliseconds, even when nothing changes, and I get input flickering. So, buttons that are pressed are briefly reported as released (and viceversa). The issue is not limited to OpenBVE, I can see it in other software with controller support on my PC, but it doesn't seem to occur on my Nintendo Switch. I guess certain adapters are just good enough for most situations, but behave oddly on certain OS/driver/software combinations.

I want to try to implement two solutions:

1. Add a small delay to input processing in the Densha plugin for classic controllers. Input is checked constantly on a loop. I suppose waiting a couple of iterations to check for flickering could mitigate the problem without adding excessive lag.

2. If 1 is not enough, allow applying emergency only above a certain brake notch (B6, for instance). This would eliminate the issue when applying power or braking moderately. Unless a faulty/altered controller is used, it's physically impossible to change from a low-medium brake notch to emergency on a single frame.

**Comment by MarcRiera** [comment] 2024-04-17 20:00
@RetentiveGOAT Could you please try this build? It includes a small delay before applying the emergency brake that I hope will mitigate the issue.

[OpenBVE_DenshaDelay_v1.zip](https://github.com/leezer3/OpenBVE/files/15016435/OpenBVE_DenshaDelay_v1.zip)

**Comment by RetentiveGOAT** [comment] 2024-04-17 20:05
Gotcha I will try this now, and report back!!

**Comment by RetentiveGOAT** [comment] 2024-04-20 13:26
The problem is solved! I no longer have the issue with this new build

**Comment by MarcRiera** [comment] 2024-04-20 21:21
Great, thanks for testing! I'll send the pull request with the patch so the fix is included in the next release.

**Closed** 2024-04-21 15:16 UTC

**Comment by leezer3** [comment] 2024-04-22 12:26
Incidentally, @MarcRiera have you seen this:
https://github.com/SukkoPera/PsxNewLib/issues/9

That suggests a 50ms delay (padded with FF FF FF in between) between actual raw data byte packets recieved from the controller when plugged into an Arduino.
I'd speculate that some (most?) adapters are dropping these.

**Comment by MarcRiera** [comment] 2024-04-22 13:31
> Incidentally, @MarcRiera have you seen this: [SukkoPera/PsxNewLib#9](https://github.com/SukkoPera/PsxNewLib/issues/9)
> 
> That suggests a 50ms delay (padded with FF FF FF in between) between actual raw data byte packets recieved from the controller when plugged into an Arduino. I'd speculate that some (most?) adapters are dropping these.

I wasn't aware of that, thanks for pointing out. It's totally possible, the world of adapters is diverse and quality varies a lot between products.
