### ISSUE TITLE
Random render glitch on in-game menu

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#473] opened 2020-05-03 02:08 UTC
### Description
A glitch has been encountered randomly at the rendering of the in-game menu, which causes characters to render incorrectly.
Once the glitch is triggered, a character will be rendered incorrectly in all in-game menu entries.
The character seen to be glitching most is "出". And the glitch causes it to be shown as "| | |". As shown below:
![renderError](https://user-images.githubusercontent.com/25097028/80896895-c795a180-8d25-11ea-9b13-2935b57556d4.png)
![renderError2](https://user-images.githubusercontent.com/25097028/80896896-c95f6500-8d25-11ea-9724-47e973d2b03d.png)
They are supposed to be "退出游戏" (Quit) and “是否要退出游戏？" (Do you really want to quit?)

### Reproduction
Unknown. Seems randomly happening. Definitely occured regularly as I have seen it many times. But when I tried to reproduce it I failed.

### Related information 
The localization selected was zh_CN.
This glitch has been present since the introduction of the in-game menu, and both before and after the introduction of the new renderer. Bug still present in 1.7.1.4.
It seems not route-related or train-related. Checking logs reveals nothing.
Triggered on both of my computers, one with Win10 1709 and one with Win10 1607.
The graphics cards of them was Intel UHD Graphics 630 and AMD Mobality Radeon HD 5000

**Comment by leezer3** [comment] 2020-05-04 00:33
I can't immediately reproduce either, which make this incredibly difficult.
Being broken in the middle of a string is *odd* - If one is broken, the rest should be as far as I can see from reading the code.

Stupid request please-
Can I have a screenshot of what it *should* look like?

We're requesting a generic sans-serif font from Windows, and whatever it's supplying you is different to what I'm getting.
(There's small 'ticks' on the top of the bars, and my font definitely has nothing of the sort. I'm halfway wondering if the string is getting corrupted somehow- https://www.compart.com/en/unicode/U+2980 is a valid unicode character)

**Comment by s520** [comment] 2020-05-04 05:43
I had a similar problem in Japanese, so I investigated and submitted a PR.
However, my problem always occurred regardless of the route or train.
So the cause may be different from your problem.

**Comment by zbx1425** [comment] 2020-05-04 07:20
> Stupid request please-
> Can I have a screenshot of what it _should_ look like?
Sure. This is it:
![renderCorrect](https://user-images.githubusercontent.com/25097028/80943406-b62dc180-8e19-11ea-8f6f-0b6fd01614e3.PNG)

> We're requesting a generic sans-serif font from Windows, and whatever it's supplying you is different to what I'm getting.
> (There's small 'ticks' on the top of the bars, and my font definitely has nothing of the sort.
Windows with Chinese locale will take 宋体 SimSun (Which is a SERIF Chinese font) as the default font. That explains why you see these tick-looking things. These are the features of the 宋体 Song typeface. In fact, almost all texts in openBVE will be of this typeface even if English language is selected. This is pretty appearant as SimSun has a bad reputation for this iconic ugly English typeface:
![winform1](https://user-images.githubusercontent.com/25097028/80943717-6ac7e300-8e1a-11ea-83d5-fbe4d45a0f04.PNG)
![winform2](https://user-images.githubusercontent.com/25097028/80943719-6bf91000-8e1a-11ea-86f7-398ad0870b5e.PNG)
> I'm halfway wondering if the string is getting corrupted somehow- https://www.compart.com/en/unicode/U+2980 is a valid unicode character)
That is definitely not the case. As you can see, the character "出" has an iconic feature, that is the center vertical stroke is slightly longer than the two side ones. The top of the glitched character matches this feature exactly. So that must be a "出" drawn incorrectly, caused its lower part failed to render and just being a same row of pixels repeating themselves.
And, once the bug is triggered, all the "出"'s in the game (at least seen in the menu) are all glitched out.

**Comment by zbx1425** [comment] 2020-05-04 07:43
> I had a similar problem in Japanese, so I investigated and submitted a PR.
> However, my problem always occurred regardless of the route or train.
> So the cause may be different from your problem.

Mine is also regardless of routes and trains. Sorry for not putting it clear enough.
So it might be a same problem though. But I cannot be sure since the way to reproduce it is unknown, and we cannot tell if it is fixed or just not reproduced. And because it does not break any functionality players are likely to skip through it so we are not likely to get informed on this.

**Comment by s520** [comment] 2020-05-04 08:19
Let's isolate the problem.

Please try the version that can be downloaded from the link below.
https://drive.google.com/open?id=1ML57Zxjg-Wzi1dhoFxniGeZmEcV7xXeS
This version outputs font table images. (base on current master)
The output paths are:
`{Assembly folder}\GlFontTables\{Font name}_{Font size}_U+{Code point offset}.bmp`
"Code point offset" represents the code point of the upper left character in the table.

If your problem is same as mine, the image obtained should be inaccurate.

**Comment by zbx1425** [comment] 2020-05-04 08:49
It seems that is not the case.
"出" is U+51FA, and is not cut off in both the unpatched and patched version.
And I had no luck on attempting to reproduce it.

**Comment by s520** [comment] 2020-05-04 08:55
That's too bad.
It would be great if we could find conditions that could be reproduced...

**Comment by zbx1425** [comment] 2020-05-04 09:02
I personally have encountered it twice this year.  
And several more times during the previous years.



I asked a few of my friends whether they have encountered this just now, and that was an affirmative. So the problem does occur often enough for people to notice.

**Comment by zbx1425** [comment] 2020-05-04 09:15
But as it was the lower part that got glitched, it seems that it is possible to be created by incorrect FontTable size. Would you please try intentionally reduce the size of FontTable to crop some characters in the FontTable, and see if its lower part became a row of pixels repeating itself like inside that picture, when rendered?

Cannot think of a reason why FontTable would be randomly glitched right now though.

**Comment by zbx1425** [comment] 2020-05-04 09:31
![image](https://user-images.githubusercontent.com/25097028/80952775-ca2eee80-8e2c-11ea-8318-171bc271a6e4.png)
Just reproduced it once again, making it the third time this year.
Sadly not on the version with FontTable export though.
But that brought me more information. Only the text on the ingame menu glitched. The messages were ok. And only the character "出" (U+51FA) has been found glitched.
And the glitch then persisted during the whole session. Drove a few stations and the menu is still glitched while the messages are not.

**Comment by s520** [comment] 2020-05-04 09:34
Your idea seems correct.
I have displayed a broken character ("ヷ") at the bottom left of the second image of my PR.
"再開ヷ" is broken.
![キャプチャ](https://user-images.githubusercontent.com/29241703/80952405-92c44000-8e34-11ea-91f5-aa5de4849022.PNG)
Your broken character ("出") seems to be clamped because it protruded the image.
see also: GL_TEXTURE_WRAP_T, https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexParameter.xhtml

**Comment by zbx1425** [comment] 2020-05-04 09:38
Nope. That is not the case. Your ヷ got black bottom part, while my "出" got repeating bottom part.
Just reproduced it on the version with FontTable output again. FontTable was not broken at all.
![image](https://user-images.githubusercontent.com/25097028/80953429-13337280-8e2e-11ea-9e73-0de1b43453ef.png)
![image](https://user-images.githubusercontent.com/25097028/80953431-1595cc80-8e2e-11ea-90c3-8fb710e42066.png)

**Comment by s520** [comment] 2020-05-04 09:48
The screenshots seemed misleading.
The menu item is active, so the colors are reversed.
The image below will match your idea.
![キャプチャ](https://user-images.githubusercontent.com/29241703/80954095-b046d900-8e37-11ea-9751-1dba983154ea.PNG)

**Comment by zbx1425** [comment] 2020-05-04 09:50
I found a way that reproduces the problem!
I started the game at 960x600 Windowed and then resized the window to 1280x720 after the game started. That means the "size" of the menu has changed. And that might be what triggered the glitch.
Given that many players use the Maximize button after the game started instead of fullscreen mode for more convenient window switching, no wonder why it is commonly encountered.

It reproduces the problem on versions before your PR but cannot reproduce it on the binary after your PR has been merged. So I guess your PR also fixed this problem.

Anyway I am curious why this is triggered as the FontTable was not broken at all. Could you please investigate it further with a version before your PR?

**Comment by zbx1425** [comment] 2020-05-04 09:55
A OT side note, I am a bit curious on your train panel. It it some kind of interesting new Ats plugin?

**Comment by s520** [comment] 2020-05-04 10:33
In the current implementation, the font size is determined by the window size when the menu is first opened.
https://github.com/leezer3/OpenBVE/blob/3426e17b8ae36a06244c6686604563f79ee39dbd/source/OpenBVE/Game/Menu.cs#L398-L405

I think there was a problem with Fonts.LargeFont (size: 21).
So when I checked, the table was broken.
![Microsoft Sans Serif_21_U+5100](https://user-images.githubusercontent.com/29241703/80956875-0b2eff00-8e3d-11ea-8480-ee89c7c6825a.png)

But when I applied my PR the table was created successfully.
![Microsoft Sans Serif_21_U+5100](https://user-images.githubusercontent.com/29241703/80957032-4e896d80-8e3d-11ea-9136-5e442b04d5ac.png)

Therefore, your problem has been resolved by my PR.

P.S
@zbx1425 
This train is a test train for touch elements created by @ginga81.

**Comment by zbx1425** [comment] 2020-05-04 10:36
Thanks a lot for your hard work!
Are you sure that also works with VeryLargeFont and EvenLargerFont?
If not, I will close this issue.

**Comment by s520** [comment] 2020-05-04 10:49
No problem :)
I haven't seen any tables that aren't printed, but tables of all sizes that are printed by the time I display the menu are undamaged.

**Comment by s520** [comment] 2020-05-04 10:59
Therefore, you can close this issue.

**Closed** 2020-05-04 11:02 UTC
