### ISSUE TITLE
Excessively high rail numbers causes a System.OutOfMemory Exception

### ISSUE THREAD

**Issue by RetentiveGOAT** [leezer3/OpenBVE#426] opened 2020-01-25 07:57 UTC
### Description

I can't load certain routes with the new renderer as it throws a System.OutOfMemory exception but I have 8 GB of RAM, 8 GB of GDDR5 RAM for my video card and an Intel Core i5-7400. I found that I cannot load the NYCT 3 line, as well as the 5, and other NYCT routes. It seems to access a lot of memory but doesn't load the route.

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Route

Download Link: https://mega.nz/#!0YRhEapQ

Key: ybQRS2o3AFBKa6Dz47UBMVDZgxxDXW8VvkQNIvL6Pzk

## Train

n/a. Applies to every train.

## Logs

Logs may be accessed through the 'Report Problem' button on the bottom left of the screen.
Please provide a log, and a crash-log if the game actually crashes.

### Related information 

* Operating system: Windows 10
* Method of control: Keyboard

**Comment by leezer3** [comment] 2020-01-25 12:40
This one seems to be being caused by some exessively high rail numberings (Over 1000), which is overflowing the available memory in 32-bit .Net.
It's not the new renderer per-se, it's just tipped over the edge.

Should be able to do something, but may only be a hacky fix as a first step.

Will try and sort, although this one is somewhat complicated

**Comment by leezer3** [comment] 2020-01-31 21:49
Fixed in the latest daily (31st January)

Will get a full build out on the site sometime in the next week or two :)

**Closed by leezer3** 2020-01-31 21:49 UTC
