### ISSUE TITLE
Crash on trains with missing flange index in between

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#611] opened 2021-04-22 15:41 UTC
### Description

Some trains have flange0.wav, flange2.wav, but no flange1.wav
This will cause crashes after the TrainManager update when checking additional flange noise due to roll angle of the car (More specifically, line 1184 in TrainManager\Car\CarBase.cs)

![image](https://user-images.githubusercontent.com/28094366/115741150-110d4f80-a3c2-11eb-8f6a-79da977b4cf6.png)

## Train
[1992TS.zip](https://github.com/leezer3/OpenBVE/files/6359512/1992TS.-.Copy.zip)

## Logs
[OpenBVE Crash- 2021.4.22[23.35].log](https://github.com/leezer3/OpenBVE/files/6359520/OpenBVE.Crash-.2021.4.22.23.35.log)
[log.txt](https://github.com/leezer3/OpenBVE/files/6359521/log.txt)

### Related information 

* Operating system: Windows 10 20H2
* Method of control: Keyboard

**Comment by Kenny-Hui** [comment] 2021-04-23 09:38
Push.
This could end up breaking a decent amount of trains, any chance this could be fixed soon?

**Comment by leezer3** [comment] 2021-04-23 10:04
I gotta get up and read the issues before I can do anything :P

I'd rather not have pushed a release quite this fast having merged the 64-bit changes last week, but yep that's a problem...

**Comment by Kenny-Hui** [comment] 2021-04-23 10:07
Nightly build will do for now, thanks!

**Closed** 2021-04-23 10:07 UTC

**Comment by leezer3** [comment] 2021-04-23 10:21
It's major enough for a release TBQH, hence why I'm pushing one at the minute.

(Alright, I suppose I could have cherry-picked all the commits other than the x64 stuff, but still)

**Comment by leezer3** [comment] 2021-04-23 10:34
1.8.0.0 should be live now.

(This was caused by some changes to deal with a developer who uses 10001 etc. for his indices, which was previously leaking memory due to allocating thousands of unused car sounds)
